name: Push Event Workflow

on: push 

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@v2
      
    - name : Install Packages 
      run : |
        pip install pytest
        pip install pytorch torchvision torchaudio cpuonly -c pytorch
      
    - name : Run tests 
      run : pytest regression_test.py